# automatically generated by the FlatBuffers compiler, do not modify

# namespace:

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class vs00_StringData(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = vs00_StringData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsvs00_StringData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    @classmethod
    def vs00_StringDataBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(
            buf, offset, b"\x76\x73\x30\x30", size_prefixed=size_prefixed
        )

    # vs00_StringData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # vs00_StringData
    def SourceName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # vs00_StringData
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # vs00_StringData
    def Data(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(
                a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4)
            )
        return ""

    # vs00_StringData
    def DataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # vs00_StringData
    def DataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0


def vs00_StringDataStart(builder):
    builder.StartObject(3)


def Start(builder):
    vs00_StringDataStart(builder)


def vs00_StringDataAddSourceName(builder, sourceName):
    builder.PrependUOffsetTRelativeSlot(
        0, flatbuffers.number_types.UOffsetTFlags.py_type(sourceName), 0
    )


def AddSourceName(builder, sourceName):
    vs00_StringDataAddSourceName(builder, sourceName)


def vs00_StringDataAddTimestamp(builder, timestamp):
    builder.PrependInt64Slot(1, timestamp, 0)


def AddTimestamp(builder, timestamp):
    vs00_StringDataAddTimestamp(builder, timestamp)


def vs00_StringDataAddData(builder, data):
    builder.PrependUOffsetTRelativeSlot(
        2, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0
    )


def AddData(builder, data):
    vs00_StringDataAddData(builder, data)


def vs00_StringDataStartDataVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def StartDataVector(builder, numElems):
    return vs00_StringDataStartDataVector(builder, numElems)


def vs00_StringDataEnd(builder):
    return builder.EndObject()


def End(builder):
    return vs00_StringDataEnd(builder)
